<div class="col-sm-12">
    <div class="row">
        <div class="content">
            <div class="col-sm-12">
                <div class="mask_banner">
                    <div style="display: table;width: 100%;height: 100%;">
                        <div style="display: table-cell;vertical-align: middle;">
                            <div class="content" style="padding: 50px 0;background: transparent;display: inline-block;width: 100%;">
                                <div class="title how_it_works">
                                    <div class="bg_line left"></div>
                                    <p>
                                        <span class="block_title">How it Works</span>
                                    </p>
                                    <div class="bg_line right"></div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="item col-sm-4">
                                        <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/HIW_1.svg">
                                        <span>Pick out some of our<br/>delicious products.</span>
                                    </div>
                                    <div class="item col-sm-4">
                                        <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/HIW_2.svg">
                                        <span>Choose a<br/>delivery date.</span>
                                    </div>
                                    <div class="item col-sm-4">
                                        <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/HIW_3.svg">
                                        <span>Healthy food<br/>arrives at your door.</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="content">
            <div class="col-sm-12">
                <div style="background-image: url('/pub/media/pub/media/wysiwyg/smartwave/porto/homepage/custom/cloth.png');    padding: 1px 0;">
                    <div class="meals-title">
                        <div class="bg_line"></div>
                        <p class="block_title"><span>Shop By Meal</span></p>
                        <div class="bg_line"></div>
                    </div>
                    <div id="banner-slider-demo-custom" class="owl-carousel owl-banner-carousel owl-bottom-narrow">
                        <div class="item">
                            <div style="position: relative;">
                                <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/meals/01_breakfast.jpg" alt="" />
                                <div class="content">
                                    <span><p>breakfast</p></span>
                                    <div class="sub-content">
                                        <a href="#" class="btn btn-default"><span>START YOUR<br/>DAY OFF RIGHT</span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div style="position: relative;">
                                <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/meals/02_lunch.jpg" alt="" />
                                <div class="content">
                                    <span><p>lunch</p></span>
                                    <div class="sub-content">
                                        <a href="#" class="btn btn-default"><span>START YOUR<br/>DAY OFF RIGHT</span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div style="position: relative;">
                                <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/meals/03_dinner.jpg" alt="" />
                                <div class="content">
                                    <span><p>dinner</p></span>
                                    <div class="sub-content">
                                        <a href="#" class="btn btn-default"><span>START YOUR<br/>DAY OFF RIGHT</span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div style="position: relative;">
                                <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/meals/04_drinks.jpg" alt="" />
                                <div class="content">
                                    <span><p>drinks</p></span>
                                    <div class="sub-content">
                                        <a href="#" class="btn btn-default"><span>START YOUR<br/>DAY OFF RIGHT</span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div style="position: relative;">
                                <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/meals/05_snacks.jpg" alt="" />
                                <div class="content">
                                    <span><p>snacks</p></span>
                                    <div class="sub-content">
                                        <a href="#" class="btn btn-default"><span>START YOUR<br/>DAY OFF RIGHT</span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div style="position: relative;">
                                <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/meals/06_dessert.jpg" alt="" />
                                <div class="content">
                                    <span><p>dessert</p></span>
                                    <div class="sub-content">
                                        <a href="#" class="btn btn-default"><span>START YOUR<br/>DAY OFF RIGHT</span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div style="position: relative;">
                                <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/meals/07_soupstacks.jpg" alt="" />
                                <div class="content">
                                    <span><p>soupstacks</p></span>
                                    <div class="sub-content">
                                        <a href="#" class="btn btn-default"><span>START YOUR<br/>DAY OFF RIGHT</span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                        require([
                            'jquery',
                            'owl.carousel/owl.carousel.min'
                        ], function ($) {
                            $("#banner-slider-demo-custom").owlCarousel({
                                autoplay: true,
                                autoplayTimeout: 5000,
                                autoplayHoverPause: true,
                                loop: true,
                                navRewind: true,
                                margin: 10,
                                nav: true,
                                navText: ["<em class='porto-icon-left-open-huge'></em>","<em class='porto-icon-right-open-huge'></em>"],
                                dots: true,
                                responsive: {
                                    0: {
                                        items:1
                                    },
                                    400: {
                                        items:2
                                    },
                                    768: {
                                        items:3
                                    },
                                    1200: {
                                        items:4
                                    }
                                }
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="homepage-bar">
            <div class="col-sm-4">
                <em class="porto-icon-dollar"></em><br/><div class="text-area"><h3>Marketing Messagezz</h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut.</p></div>
            </div>
            <div class="col-sm-4">
                <em class="porto-icon-chat"></em><br/><div class="text-area"><h3>Marketing Messagezz</h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut.</p></div>
            </div>
            <div class="col-sm-4">
                <em class="porto-icon-truck"></em><br/><div class="text-area"><h3>Marketing Messagezz</h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut.</p></div>
            </div>
        </div>
    </div>
</div>