<div id="banner-slider-demo-1" class="owl-carousel owl-banner-carousel owl-middle-narrow">
    <div class="item">
        <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/hero_1400_homepage_slider.jpg" alt="" />

        <div class="content_type1">
            <h2>HUGE <b>SALE</b></h2>
            <p>Now starting at <span>$99</span></p>
            <a href="#">Shop now &gt;</a>
        </div>

        <div class="popup_content">
            <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/apple_radish_flat.svg" class="top_logo">
            <h3>Real Food Ready-Made Delivered</h3>
            <p>Get delicious and satisfying plant-based meals delivered fully prepared and fresh so you can get out of the kitchen and on with your life.</p>
            <a href="#" class="button shop_button"><span>SHOP NOW</span></a>
        </div>

    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'owl.carousel/owl.carousel.min'
    ], function ($) {
        $("#banner-slider-demo-1").owlCarousel({
            items: 1,
            autoplay: false
        });
    });
</script>