<div class="col-sm-6 item f-right">
    <div class="content col-sm-12">
        <p class="top_note">See more recipes</p>
        <div class="col-sm-12">
            <h2>MamaSezz: <b class="black">"Try these Recipes!"</b></h2>
        </div>
        <div class="col-sm-5">
            <div class="view_img">
                <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/brocsalad.png" alt=""/>
            </div>
        </div>
        <div class="col-sm-7">
            <h3>Delicious Avocado Ice Cream</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua adipiscing elit, sed do eiusmod tempor incididunt... <a href="#">Read more ></a></p>
        </div>
    </div>
</div>
</div>