<div class="row">
    <div class="col-sm-6 item f-left">
        <div class="content col-sm-12">
            <p class="top_note">See more articles</p>
            <div class="col-sm-12">
                <h2>The Raw Truth</h2>
            </div>
            <div class="col-sm-5">
                <div class="view_img">
                    <img src="/pub/media/wysiwyg/smartwave/porto/homepage/custom/avocado_FPO.jpg" alt="" />
                </div>
            </div>
            <div class="col-sm-7">
                <h3>Where do you get your protein?</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua adipiscing elit, sed do eiusmod tempor incididunt... <a href="#">Read more ></a></p>
            </div>
        </div>
    </div>